# Generated by Django 5.0.6 on 2024-05-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
